### ISSUE TITLE
make /time default to get

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#103]

**Comment by LunaUrsa** [comment]
So the /time command is two different commands grouped together:
/time get <user>
/time set <timezone>

I could change this to be:
/time <user> <optional:timezone>

This way:
Anyone           could /time @user and get that user's timezone.
Anyone           could /time @me <timezone> to set their own timezone
Moderators(?) could /time @user <timezone> to set someone else's timezone

**Comment by LunaUrsa** [comment]
Both /time and /birthday are (set) commands, the (get) command is /profile
