### ISSUE TITLE
Load in custom emojis into /start-here

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#106]

**Comment by LunaUrsa** [comment]
This is complete
![image](https://user-images.githubusercontent.com/1836049/171067005-70300dde-71ad-4443-a277-529913039505.png)

![image](https://user-images.githubusercontent.com/1836049/171067013-9c56ba92-6e4b-48de-bfb3-af382fa6ea04.png)

![image](https://user-images.githubusercontent.com/1836049/171067026-cf68c821-23c0-461e-b2a8-5d1e0651bc7c.png)
