### ISSUE TITLE
Update welcome messages

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#116]
When a user joins but doesn't accept the Welcome message they're still "pending" and their username does not display correctly. Also, if i user leaves the guild their nickname changes to @invalid-user. We could change this to just display user.nickname but i think we're better than that. 

Make the following changes:

1. Store the user's information in the DB when they join
2. Check this user every X seconds to see if member.pending = false
3. When member.pending = false, send the welcome message
4. Store the welcome message ID in the member's userDB
5. When the user leaves the guild, look up the welcome message ID and delete it

**Comment by LunaUrsa** [comment]
We have a new plan for this, but Im too lazy to detail it right here, if you see this comment come talk to me

**Comment by LunaUrsa** [comment]
The new plan has been implemented: When someone joins the guild they need to click the "welcome" button, and this sends a message to #general. The delay between join and clicking should populate the cache?
