### ISSUE TITLE
Allow aliases in the drug name lookup

### ISSUE THREAD

**Issue by ajar** [TripSit/tripsit-discord#120]
Right now, it's just checking the display name or value in autosuggestion for param `substance` in actions `dose`, `idose`, etc. Users should be able to say that they took "ecstasy" and have it resolve to MDMA, or "Klonopin" and have it resolve to clonazepam. 

![CleanShot 2022-05-29 at 22 42 02@2x](https://user-images.githubusercontent.com/612499/170909003-02b04944-3fed-4635-a878-106e2e86cbb0.png)

Slang terms, trade names, and an exhaustive list of common names will later be added in—I have a data set I can load into the existing structure here—for the best UX, lowering the barrier to forming a habit around the practice of keeping track of usage. There are two good approaches to my mind right now, and I'm open to feedback.

### Approach A

Possibly the easiest solution would be to expand something like "MDMA" in the list to include up to 3-4 of the most common alternate names in parentheses, then still send back the primary name as the value. See example below.

![CleanShot 2022-05-29 at 23 06 59@2x](https://user-images.githubusercontent.com/612499/170910019-4dcc9c56-2348-426b-925d-fccd2601660a.png)

### Approach B

The second proposal is to expand something like "MDMA" prior to to include separate entries—all resolving to the same end value passed back to the action handler—and this is the one I aim to take first as it will be most intuitive, I think. Here's an example for 4-MMC (mephedrone, drone, cat piss, M-CAT, 4-methylmethcathinone).

<img width="239" alt="CleanShot 2022-05-29 at 23 14 12@2x" src="https://user-images.githubusercontent.com/612499/170910607-9391e266-b244-4d8d-87ef-6ee55360eb6f.png">

Currently, if you enter "4-MMC," you don't resolve to anything. And probably we'd want to make sure that when multiple matches show for the same substance, we don't go displaying every nickname as separate lines. Instead, take the first match for whatever was entered and suggest it.

**Comment by ajar** [comment]
This winds up being an **Approach C**, for posterity's sake, which was originally **Plan A**: the one that really makes sense and feels intuitive. Looks like this and works well:

![image](https://user-images.githubusercontent.com/612499/171078121-992c4e9d-0125-4c3b-b488-738d8e74c223.png)

**Comment by ajar** [comment]
More will be done for this—a lot more, including injection of many _many_ more aliases—but discussion is required.

**Comment by LunaUrsa** [comment]
Great work on this!
