### ISSUE TITLE
Have people react to the /hydrate output to get internet points

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#13]
The more reactions you leave, the more Sparkle Points you get!
Get enough sparkle points and you're on your way to your first Aqua Badge!
Collect enough Aqua Badges and we'll welcome to you the H-2-Flow Platinum Club(tm)!

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/172943577-d5ddabea-ba81-4d60-90b8-4f9fd694886c.png)
