### ISSUE TITLE
Add Connect & Disconnect Messages to IRC Bridging

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#138]

**Comment by ajar** [comment]
Reviewing this now.

**Comment by LunarUrsan** [comment]
When someone joins/parts a channel on IRC these messages do not make it to discord.

When you're talking to someone on irc from discord and they leave, you have no way of knowing.

One solution would be to show join/part messages in the discord channel, however, this is super noisy especially for a channel like #sanctuary. 

Another (better, more complicated) solution would be to track when the IRC user last talked. If they quit the irc server and if they talked in the last X minutes (15?) then show a part message. 

This will require DB connection to store last talked times. Discord already does this for every message as part of the EXP system. I need a bridge channel so i can test messages from IRC.

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/176735699-a2b62cc8-8ab9-4fcf-a1df-233e7a07f7c7.png)
