### ISSUE TITLE
Birthday erroneously adjusted by GMT offset in profile command

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#151]

**Comment by LunaUrsa** [comment]
Could i get an example of this? The code is currently using the "relative" format for the date:

![image](https://user-images.githubusercontent.com/1836049/173066651-088c6096-f47b-47f8-8cc8-9dfe812823af.png)

birthday is set like: 

![image](https://user-images.githubusercontent.com/1836049/173066749-50e81818-a70f-4ffb-9d82-63d92361c1ab.png)

**Comment by LunaUrsa** [comment]
I get that this could be smarter but i don't see why it wouldn't display a relative time to the user?
