### ISSUE TITLE
Change nick of TSDiscord to be shorter, maybe 2 chars?

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#157]
When left-aligned and not aligned by the username, it is quite difficult for me to keep track of Discord usernames chatting via `TSDiscord` right now. Propose making it as short as possible for a more natural feel.

**Comment by LunaUrsa** [comment]
@derelictions  @BuddhaDharma 

Can one you make this change? I have the "TS" account we can use? I believe winter said they found a way to merge telegram into discord so it's all one bot on IRC. If we can have that bot called TS that'd be great. If we can share this IRC account with my discord bot that'd be nifty, but if need be i can give up the TS nickname. The discord bot talks to tripbot directly so it doesn't really need a nickname even.

**Comment by LunaUrsa** [comment]
This is completed!
![image](https://user-images.githubusercontent.com/1836049/173093589-7a0171e8-1b8a-4c99-8b0d-c15f66c5b3de.png)
