### ISSUE TITLE
disable "anyone can unarchive" and "anyone can invite" for tripbot created tripsit and tripsitter threads

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#160]
![image](https://user-images.githubusercontent.com/1836049/173395449-0feee301-5362-4e05-acc0-73b7a2d9f113.png)
https://support.discord.com/hc/en-us/articles/4404809613847-Threads-Moderation-FAQ

**Comment by LunaUrsa** [comment]
This is completed!
