### ISSUE TITLE
IRC-room overhaul

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#164]
1) Make an #IRC intro page like #tripsit has with buttons that have the following options:
a) I am banned and want to appeal!
b) I cannot connect and don't know why!
c) I have general feedback on the IRC!

When a user clicks those buttons a modal opens asking them questions:
a) Why are you banned? What will you do to ensure this wont happen in the future?
b) What error does the IRC give you? What is your IP address? Are you connecting with a VPN?
c) What is your feedback?

When the modal is submitted a few things happen:
1) A private thread is created in #irc that pings the user, IRC Admin and IRC Operators.
(Note: we'll need to clean up the operator list so that only people who can help on IRC get the ping) 
2) A PM is sent to IRC Admin saying someone needs help in #irc and links to the thread.

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/174085781-63f525ce-2080-423d-885d-b3e7351f06e1.png)

**Comment by BuddhaDharma** [comment]
Very cool
