### ISSUE TITLE
Birthday may be affected by timezone issues

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#185]

**Comment by ajar** [comment]
Can we just use a static date field vs. relative for this one? Also can look to see if the date passed already, and if so then add a year so the field becomes "next birthdate." If it's currently their birthday, we can notate that specifically by applying their TZ GMT offset if stated. If we are talking about the profile card

**Comment by LunaUrsa** [comment]
We now use a static field in /profile!
