### ISSUE TITLE
Setup "badwords" functionality

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#234]

**Comment by spr1t3-0** [comment]
This is also already done, right?

**Comment by LunarUrsan** [comment]
This was completed, but it turns out regex is complicated, so it was super spammy, and despite having the document up for weeks everyone was surprised by this, so it's disabled for now.

Also, since the time this idea was spawned and now, the IRC was shut down, and the discord 'badword' filter has been expanded, so we're putting this down for now
