### ISSUE TITLE
Close help requests when users leave the server

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#239]

**Comment by LunaUrsa** [comment]
We could likely just delete after 7 days like tripsit threads are regardless if they're in the guild or not

**Comment by LunaUrsa** [comment]
If the user leaves the guild in the middle of the session, the thread should at least reflect this and say something

**Comment by spr1t3-0** [comment]
You mean tripbot should send smth like 'user left the guild' to the thread?

**Comment by LunaUrsa** [comment]
> You mean tripbot should send smth like 'user left the guild' to the thread?

Yes, exactly, at the very least

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/191093799-b0e5f215-2640-4162-b7ff-928f59f2fb25.png)
