### ISSUE TITLE
combo does not work in PM

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#263]

**Comment by LunaUrsa** [comment]
Seems to be broken about 75% of the time EG:
![image](https://user-images.githubusercontent.com/1836049/186921827-8917f555-c01b-43dd-ac88-483a20227d62.png)

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/188903351-fe54d30a-4ce7-4ce6-8893-31724dd562b6.png)
