### ISSUE TITLE
Make /helpline

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#317]
"Hey friend! It seems like you're having a tough time right now. If you are experiencing a mental health crisis, please reach out to your local crisis line:

US: call 988 or text HOME to 741741
Canada: call 1-833-456-4566 or text HOME to 74141
UK: call 116 123 or text SHOUT to 85258

Check https://blog.opencounseling.com/suicide-hotlines/ to find crisis lines for all other countries. "

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/193424361-2583d459-ebc3-40ea-ba2b-57590ea44e82.png)
