### ISSUE TITLE
EXP in voice chats?

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#343]
The plan for voice exp:
1) Will be separate from normal exp while we're in this beta phase

2) Will only generate you are:
2a) In a non-afk, not 24-7-radio voice channel
2b) With another person (not alone)
2c) Not muted/deafened
2d) Without the needshelp role
2e) Without any bot in the room (not listening to music)

3) For every minute in voice chat:
3a) "(15 to 25) / 2" experience is generated
3b) Experience is given to the category the voice chat is under. EG: If you're in a Tent you get General.

**Comment by LunaUrsa** [comment]
15 - 25 (current spread) experience is generated once per minute while a user is connected to a voice room with one other human (not bot) while not muted, deafened or idle.

**Comment by LunaUrsa** [comment]
Voice EXP is tracked separately from regular EXP as a trial.
Voice EXP will have categories: General, Tripsitter, Developer, Team.
