### ISSUE TITLE
Multiple modal submits

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#349]
If someone starts a modal, quits it, and then starts it again, it will submit two issues

**Comment by spr1t3-0** [comment]
Could not reproduce this error.

**Comment by LunaUrsa** [comment]
This has been resolved! Need to add interaction Id check

![image](https://user-images.githubusercontent.com/1836049/201105136-5e049b43-6f95-47cd-906d-589b4738c7e5.png)
