### ISSUE TITLE
Make this https://codepen.io/cyberoxide/full/BaNarGd

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#38]

**Comment by LunaUrsa** [comment]
This is created: 
![image](https://user-images.githubusercontent.com/1836049/166119354-99f7fde6-8226-447d-a687-adae272a7458.png)
![image](https://user-images.githubusercontent.com/1836049/166119355-101dbd07-daa1-482d-a3d3-aeae842d307a.png)
