### ISSUE TITLE
Add link to factsheet/wiki for detected substance to /combo and /drug errors

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#397]
Add a note to "drugname has no interactions" that its case sensitive.... and also add links to relevant wiki/factsheet/etc

This issue was submitted by yule trees 🎄 in TripSit

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/209448144-f16b9a77-6fc1-4bac-8fa2-29da3a7e2c2d.png)
