### ISSUE TITLE
Parsing issue in /drug alias?

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#398]
Check out the aliases for DOB, it looks like something is parsing the commas weirdly

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/208965109-81918ce5-6143-423c-a371-edda3fb047fe.png)

**Comment by spr1t3-0** [comment]
No parsing issue here, indeed the 'aliases' section of DOM in the dataset looks like this: 
`"aliases": [
      "and peace)",
      "stp",
      "stp (serenity",
      "tranquility"
    ],`

**Comment by LunaUrsa** [comment]
Lovely, we'll clean this up as we review the db
