### ISSUE TITLE
Typos - Please add all typos to this issue!

### ISSUE THREAD

**Issue by LunaUrsa** [TripSit/tripsit-discord#424]
Instead of an issue for each typo, please make a comment here when you find them. I will react to the comment when it's fixed. 

Thank you! Even these tedious improvements are vital to a great experience; please be nitpicky!

**Comment by WorriedHobbiton** [comment]
/help - typo in command description (bout)

/Slowmode off - command description reads “turn on slow mode”

/Triptoys
Draw a 3d mandala link - 404 not found 

Plasma pong link directs to a download page (unsure if this is expected)

/EMS - last link (Open Counseling Suicide Hotline List) directs to a page about searching for a therapist near you. Should it be the suicide-hotlines page from the same site? 
Currently: https://www.opencounseling.com/

Suggested: https://blog.opencounseling.com/suicide-hotlines/

**Comment by emerjay** [comment]
Can you explain more about it? Maybe attach some pictures to easier illustrate.

**Comment by LunaUrsa** [comment]
"you've" instead of "you're" when failing a raid
