### ISSUE TITLE
Nasal Spray Calculator

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#436]
You input

how many mg per spray you want
how many mg the bottle excretes per spray
the amount of solvent used

and it calculates the amount of substance that you need to use

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/218758611-c84f1e34-0f5b-43ac-90da-bd89b028f131.png)

**Comment by spr1t3-0** [comment]
done
