### ISSUE TITLE
Combos of the same class should show proper info

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#446]
If you /combo two different opioids, the bot says that combo info isnt known, but we know that mixing opioids isnt great. 

Have the bot respond with something to the effect of “These medications belong to the same medication classification (<class>). While all of the substances within this classification have similar subjective effects their potency can vary greatly which may increase the risk of overdose when used in combination” 

We can probably do this for every class?

**Comment by spr1t3-0** [comment]
i would maybe say 'substancce' instead of 'medication' to make it more general. 
But yeah, i think it applies to every class.

**Comment by LunaUrsa** [comment]
![image](https://github.com/TripSit/TripBot/assets/1836049/7333809e-54b4-4c15-bc29-4bae99a1fc28)
