### ISSUE TITLE
Make /guides that shows the Wiki guides

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#448]
Should be fairly simple

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/221368815-465a1455-9b01-488b-82b9-194329c0d525.png)

**Comment by spr1t3-0** [comment]
https://wiki.tripsit.me/api.php?action=query&list=categorymembers&cmtitle=Category:Guides&format=json
