### ISSUE TITLE
Give tripbot some DB stats (28th March birthday, UTC timezone, LVL 100...?)

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#455]
Title 

This issue was submitted by Hipperooni🐧 in TripSit

**Comment by LunaUrsa** [comment]
I gave the bot the April 3rd birthday, which is when the initial python bot was committed to the repo.
I gave it a Chicago timezone cuz that's closest to where I live, debating doing UTC, not sure
I would give it a bunch of experience but that would taint the leaderboards, maybe we can do something with g.profile and g.levels to return specific data for tripbot?
