### ISSUE TITLE
Can't break the combo in counting-tokens when joining the round

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#485]
It prompts to type the mismatching number again to confirm the combo-breaking, but that's not compatible with the cooldown rule. 
        
        This issue was submitted by ҉ 𝙛𝙤𝙜𝙜𝙮 ҉ ('𝙚𝙮/'𝙚𝙢) in TripSit

**Comment by spr1t3-0** [comment]
expected behavior i guess :)
