### ISSUE TITLE
make /profile to show words, time, karma

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#49]

**Comment by ajar** [comment]
I'd love to take part in this one if possible.

**Comment by AJAr** [comment]
I'd love to take part in this one if possible.

**Comment by LunaUrsa** [comment]
I've assigned to you, go for it, show me what you can do!

**Comment by ajar** [comment]
> I've assigned to you, go for it, show me what you can do!

Are we storing data on words and time right now?

**Comment by LunarUrsan** [comment]
We talked in discord but FTR: We're using mee6 words/experience right now, but we hope to re-build our own EXP system. 

Time data comes from the Member info, something like "guildJoinDate"

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/172269583-7bc50503-2ca8-42b2-8c1a-517b2fb89177.png)

**Comment by LunaUrsa** [comment]
![image](https://user-images.githubusercontent.com/1836049/172269583-7bc50503-2ca8-42b2-8c1a-517b2fb89177.png)
