### ISSUE TITLE
Look into /report errors

### ISSUE THREAD

**Issue by LunaUrsa** [TripSit/tripsit-discord#592]
also looks like autofill on 'target' is not functioning correctly
        
        This issue was submitted by Hipperooni🐧 in TripSit

**Comment by theimperious1** [comment]
Still a problem? This probably was the same error that was breaking a bunch of other mod tools, the label being too long or attempts to use the command on users who were no longer in the guild. Both of those should be fixed either now or upon merging latest mod tools fix
