### ISSUE TITLE
Only allow one non-archived sitting thread per user at a given time

### ISSUE THREAD

**Issue by ajar** [TripSit/tripsit-discord#63]
Suggested fix without thinking too hard about it...

- When the button is pressed to create a session, assign the `@needs-help` role first.
- When a request is received by a user with that role, short-circuit normal action logic and...
- ... instead, create an ephemeral message that pings the user inside of the active thread.
- When all sessions are archived, remove the `@needs-help` role, restoring normal functionality.

![CleanShot 2022-05-12 at 00 55 11@2x](https://user-images.githubusercontent.com/612499/167994946-6758f5ab-7cd1-4077-80a7-fe4c8d160211.png)

**Comment by ajar** [comment]
Could make an ephemeral message for their eyes only underneath the main part as well which links them to the thread...

![CleanShot 2022-05-12 at 01 05 56@2x](https://user-images.githubusercontent.com/612499/167996423-65145baf-bd7e-45dc-b474-321c8f4f34eb.png)

**Comment by LunaUrsa** [comment]
So this was already coded i just forgot: https://github.com/TripSit/tripsit-discord-bot/blob/main/src/commands/guild/tripsitme.js#L55

![image](https://user-images.githubusercontent.com/1836049/168081674-75260a27-5f98-4147-b59b-a3a1207ec060.png)
