### ISSUE TITLE
The page buttons break randomly

### ISSUE THREAD

**Issue by LunarUrsan** [TripSit/tripsit-discord#75]

**Comment by LunaUrsa** [comment]
They break every so often but i dont know why. 
I double checked and im using the most popular discord.js page package (discordjs-button-pagination)

**Comment by ajar** [comment]
I can screw around with this. Being too lazy personally to actually diagnose my DB issue, I'm gonna rig up a slightly more lenient dev mode and PR for consideration. Why spend 50 minutes figuring out with relief what I could just as easily spend 4-6 hours circumventing?

**Comment by LunaUrsa** [comment]
I  havn't seen this come up in a while
