### ISSUE TITLE
Add the moderators name to the end of a ban reason when banning through tripbot

### ISSUE THREAD

**Issue by LunaUrsa** [TripSit/tripsit-discord#783]
Should be ez
        
        This issue was submitted by Hipperooni 🐧 in TripSit

**Comment by AlanaRm-rf-me** [comment]
I dont mean to hijack this into a list of mod functions, but..

# Hijacking for a list for moderation functions
- Modmail (?)
- Appeal system, will take alook at other bots real quick and see how they do it, but shouldn't be hard to have a webhook, execute /unban through a function call or an else statement of lol get rekt denied on a webform thru JS? just depends if your DB for ts.me 
- A class to call for a function that bans moonbear if there is any nap hours before 3:30pm?
